/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package effectivejava;

import java.util.HashSet;
import java.util.List;

import effectivejava.ch2.builder.Athlete;
import effectivejava.ch2.builder.BasketballPlayer;
import effectivejava.ch2.builder.SponsoredAthlete;
import effectivejava.ch2.builder.SponsoredAthlete.Sponsor;
import effectivejava.ch2.static_factory_methods.washeddishes.WashedDishes;
import effectivejava.ch4.inheritance.BadCountedHashSet;
import effectivejava.ch4.inheritance.CountedSet;

public class App {

    public static void main(String[] args) {
			inheritance();
			
    }

		static void inheritance() {
			BadCountedHashSet<String> badNames = new BadCountedHashSet<>();
			CountedSet<String> names = new CountedSet<>(new HashSet<>());

			badNames.addAll(List.of("Gerald", "Betty", "Marcy"));
			names.addAll(List.of("Gerald", "Betty", "Marcy"));
			System.out.println("badNames count: " + badNames.getAddCount()); // prints 6.
			System.out.println("names count: " + names.getAddCount()); // prints 3.

		}

		static void builder() {
			//	Type of returned object from static factory method (i.e. DishWasher) is hidden from consumer.
			WashedDishes.getInstance().printDrawback();    

			// Instantiating an Athlete object using the builder pattern
			Athlete athlete = new Athlete.Builder(168.0, 57.5)
				.bench(60.0)
				.squat(100.25)
				.deadlift(105.1)
				.build();

			System.out.println(athlete);

			// Instantiating an object using the builder pattern, and that inherited builder methods.	
			SponsoredAthlete lebron = new BasketballPlayer.Builder(84)
				.addSponsor(Sponsor.NIKE) // inherited method, observe how it returns a BasketballPlayer.Builder instance and no typecasting is required
				.standingVertical(45) 
				.build();

			System.out.println(lebron);
		}
}
