/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hiroshisprojects.effectivejava;

import com.hiroshisprojects.effectivejava.ch2.static_factory_methods.washeddishes.WashedDishes;

public class App {

    public static void main(String[] args) {

			// Type of returned object from static factory method (i.e. DishWasher) is hidden from consumer.
			WashedDishes.getInstance().printDrawback();    
    }
}
