/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hiroshisprojects.effectivejava;

import com.hiroshisprojects.effectivejava.collections.Collections;

public class App {

    public static void main(String[] args) {
        Collections.main(new String[]{ "foo" });
		System.out.println("----------------");
        Collections.main(new String[]{ "bar" });
    }
}
